fix: default value in verify-signed-rpms
The value of the `FAIL_UNSIGNED` parameter of the `verify-signed-rpms`
Task is used when calling the `rpm_verifier` binary. An empty string
value is not a valid value result in this error:

```
Usage: rpm_verifier [OPTIONS]
Try 'rpm_verifier --help' for help.

Error: Invalid value for '--fail-unsigned': '' is not a valid boolean.
```

This commit changes the default value to `"false"`. This is both valid
and inline with ADR-14:
https://konflux-ci.dev/architecture/ADR/0014-let-pipelines-proceed.html

Signed-off-by: Luiz Carvalho <lucarval@redhat.com>